name: Sync image to GitHub

on:
  push:
    tags:
      - '*_*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          IFS='_' read -ra PARTS <<< "$TAG_NAME"
          IMAGE="${PARTS[0]}"
          TAG="${PARTS[1]}"
          docker pull $IMAGE:$TAG
          docker tag $IMAGE:$TAG ghcr.io/${{ github.repository_owner }}/${IMAGE}:${TAG}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE}:${TAG}