name: Sync image to GitHub

on:
  push:
    tags:
      - '*:*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and tag the Docker image
        run: |
          IMAGE_NAME="${GITHUB_REF#refs/tags/}"
          IFS=':' read -ra IMG <<< "$IMAGE_NAME"
          IMAGE="${IMG[0]}"
          TAG="${IMG[1]}"
          docker pull $IMAGE_NAME
          docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/${IMAGE}:${TAG}

      - name: Push the Docker image to GitHub Container Registry
        run: |
          IMAGE_NAME="${GITHUB_REF#refs/tags/}"
          IFS=':' read -ra IMG <<< "$IMAGE_NAME"
          IMAGE="${IMG[0]}"
          TAG="${IMG[1]}"
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE}:${TAG}

